version: "3"
services:
    languagetool:
        build:
            dockerfile: Dockerfile
            context: ./
        container_name: languagetool
        environment:
            - VERSION=6.3
            #- langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
            - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
            - Java_Xmx=1g  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
        volumes:
            - ${PWD}/ngrams/data:/ngrams
    api-node:
        build:
            context: ./api-node
            dockerfile: Dockerfile
        image: api-node
        environment:
            - PORT=4000
    api-python:
        build:
            context: ./api-python
            dockerfile: Dockerfile
        image: api-python
        volumes:
          - ${PWD}/nltk_data:/root/nltk_data
        tty: true
    htdocs:
        image: httpd:2.4
        volumes:
          - ${PWD}/frontend/dist/languagetool:/usr/local/apache2/htdocs
          - ${PWD}/semester/dist/semister:/usr/local/apache2/htdocs/semister
        restart: always
    nginx:
        image: nginx:latest
        ports:
          - 85:80
        restart: always

        volumes:
          - ${PWD}/nginx/conf.d:/etc/nginx/conf.d/
    
