version: "3"
services:
    languagetool:
        build:
            dockerfile: Dockerfile
            context: ./
        container_name: languagetool
        ports:
            - 8010:8010  # Using default port from the image
        environment:
            - VERSION=6.3
            #- langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
            - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
            - Java_Xmx=1g  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
        volumes:
            - ${PWD}/ngrams/data:/ngrams
    api-node:
        build:
            context: ./api-node
            dockerfile: Dockerfile
        image: api-node
        environment:
            - PORT=4000
        ports:
          - 4000:4000
    api-python:
        build:
            context: ./api-python
            dockerfile: Dockerfile
        image: api-python
        ports:
          - 8000:8000
        volumes:
          - ${PWD}/nltk_data:/root/nltk_data
    htdocs:
        image: httpd:2.4
        volumes:
        - ./frontend/dist:/usr/local/apache2/htdocs
        restart: always
    nginx:
        image: nginx:latest
        ports:
        - 84:80
        restart: always

        volumes:
        - ${PWD}/nginx/conf.d:/etc/nginx/conf.d/
    